// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprHEG2pgWwCky6BdUt_jAxkN_Irv3W4k',
    appId: '1:730099336727:web:dc5e56dbb33dd4f88a3e52',
    messagingSenderId: '730099336727',
    projectId: 'zoopath',
    authDomain: 'zoopath.firebaseapp.com',
    storageBucket: 'zoopath.firebasestorage.app',
    measurementId: 'G-HP4ELB50SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLI_XL_AZuEeVVcsXdZ2nYluR7CgoSpy0',
    appId: '1:730099336727:android:92c67c45e6424d9c8a3e52',
    messagingSenderId: '730099336727',
    projectId: 'zoopath',
    storageBucket: 'zoopath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkCthbYB1nxm9EAVyw9E0aAAJuqWBTsNs',
    appId: '1:730099336727:ios:5d51b9f4384e295b8a3e52',
    messagingSenderId: '730099336727',
    projectId: 'zoopath',
    storageBucket: 'zoopath.firebasestorage.app',
    iosBundleId: 'com.example.projectZoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkCthbYB1nxm9EAVyw9E0aAAJuqWBTsNs',
    appId: '1:730099336727:ios:5d51b9f4384e295b8a3e52',
    messagingSenderId: '730099336727',
    projectId: 'zoopath',
    storageBucket: 'zoopath.firebasestorage.app',
    iosBundleId: 'com.example.projectZoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDprHEG2pgWwCky6BdUt_jAxkN_Irv3W4k',
    appId: '1:730099336727:web:c5f1768a978a78698a3e52',
    messagingSenderId: '730099336727',
    projectId: 'zoopath',
    authDomain: 'zoopath.firebaseapp.com',
    storageBucket: 'zoopath.firebasestorage.app',
    measurementId: 'G-F0NT4DY67Z',
  );
}
